import type { StepRun, StoreState } from "@/lib/domain/types";
import { PACKAGES } from "@/lib/capabilities/registry";
import { getCrew } from "@/lib/capabilities/crews";

function demoSteps(slug: string): StepRun[] {
  const crew = getCrew(slug);
  const pkg = PACKAGES.find((item) => item.slug === slug);
  const protocol = pkg?.protocol ?? ["Research", "Draft", "Verify"];
  const stamp = "2026-09-08T16:00:00.000Z";
  const steps: StepRun[] = protocol.map((name, index) => {
    const role = crew.roles[Math.min(index, crew.roles.length - 1)];
    return {
      id: `step_${slug}_${index}`,
      name,
      status: "succeeded",
      detail: `${role.role}: ${role.goal}. Cannot: ${role.cannot.join(", ")}.`,
      startedAt: stamp,
      endedAt: stamp,
      role: role.role,
      tokens: 420 + index * 80,
      durationMs: 900 + index * 400,
    };
  });
  steps.push({
    id: `step_${slug}_broker`,
    name: "Tool broker",
    status: "denied",
    detail: "WRITE_DENIED_IN_TEST: send_email is blocked until supervised mode and a payload-bound approval.",
    startedAt: stamp,
    endedAt: stamp,
    role: "Policy",
    tokens: 0,
    durationMs: 40,
  });
  return steps;
}

const TENANT = "tenant_acme";
const WORKSPACE = "ws_acme";
const USER = "user_gabriel";

export const DEMO_TENANT = TENANT;

export function buildSeed(): StoreState {
  return {
    workspace: {
      id: WORKSPACE,
      tenantId: TENANT,
      name: "Acme",
      slug: "acme",
      createdAt: "2026-09-01T08:00:00.000Z",
    },
    memberships: [
      {
        id: "mem_gabriel",
        tenantId: TENANT,
        workspaceId: WORKSPACE,
        userId: USER,
        name: "Gabriel",
        email: "gabriel@acme.com",
        role: "owner",
      },
    ],
    profile: {
      id: "profile_acme",
      tenantId: TENANT,
      name: "Acme",
      website: "https://acme.com",
      summary:
        "B2B software for construction teams. Acme helps site managers plan, quote and coordinate crews without a patchwork of spreadsheets.",
      industry: "Construction software",
      size: "SME — ~50 people",
      region: "Europe",
      tags: ["B2B", "Construction", "SaaS", "Europe"],
      input: "https://acme.com",
      completedAt: "2026-09-08T09:12:00.000Z",
      claims: [
        {
          id: "claim_1",
          kind: "fact",
          label: "What you do",
          value: "Site operations software for construction SMEs: planning, quoting, crew coordination.",
          sourceUrl: "https://acme.com",
          confidence: 0.92,
        },
        {
          id: "claim_2",
          kind: "fact",
          label: "Who you serve",
          value: "General contractors and site managers in France and Benelux, typically 20–200 people.",
          sourceUrl: "https://acme.com/customers",
          confidence: 0.84,
        },
        {
          id: "claim_3",
          kind: "fact",
          label: "What you care about",
          value: "Time-to-quote, weekend coverage, and not inventing prices in customer replies.",
          sourceUrl: "https://acme.com/about",
          confidence: 0.8,
        },
        {
          id: "claim_4",
          kind: "hypothesis",
          label: "Ideal customer",
          value: "Mid-size contractors running 3+ simultaneous sites.",
          confidence: 0.55,
        },
        {
          id: "claim_5",
          kind: "hypothesis",
          label: "Primary channel",
          value: "Inbound from LinkedIn and partner referrals, not paid search.",
          confidence: 0.48,
        },
        {
          id: "claim_6",
          kind: "missing",
          label: "Offer catalog",
          value: "Approved price list and weekend-coverage terms are not in the profile yet.",
          confidence: 0,
        },
        {
          id: "claim_7",
          kind: "missing",
          label: "Delivery constraint",
          value: "Standard lead time for on-site rollout is unknown.",
          confidence: 0,
        },
      ],
    },
    packages: PACKAGES,
    missions: [
      {
        id: "mission_request",
        tenantId: TENANT,
        packageSlug: "request-analysis",
        packageVersion: "0.4.0",
        name: "Analyze incoming customer requests",
        state: "testing",
        draftVersionId: "mv_request_1",
        createdAt: "2026-09-07T10:00:00.000Z",
        updatedAt: "2026-09-08T21:40:00.000Z",
      },
      {
        id: "mission_content",
        tenantId: TENANT,
        packageSlug: "content-draft",
        packageVersion: "0.1.0",
        name: "Sourced LinkedIn drafts",
        state: "testing",
        draftVersionId: "mv_content_1",
        createdAt: "2026-09-08T08:00:00.000Z",
        updatedAt: "2026-09-08T18:12:00.000Z",
      },
      {
        id: "mission_meeting",
        tenantId: TENANT,
        packageSlug: "meeting-prep",
        packageVersion: "0.1.0",
        name: "Meeting briefs",
        state: "ready",
        draftVersionId: "mv_meeting_1",
        activeVersionId: "mv_meeting_1",
        createdAt: "2026-09-06T09:00:00.000Z",
        updatedAt: "2026-09-08T16:00:00.000Z",
      },
    ],
    missionVersions: [
      {
        id: "mv_request_1",
        tenantId: TENANT,
        missionId: "mission_request",
        version: 1,
        immutable: false,
        outcome: "Structured need and prepared reply for inbound customer requests.",
        knowledgeSourceIds: ["src_profile", "src_request_104", "src_catalog"],
        instructions:
          "Never invent prices. If a delivery constraint is missing, name it. Reply in French when the request is in French. Escalate legal or margin questions.",
        tools: ["read_approved_sources", "create_artifact"],
        operatingMode: "test",
        budgetEur: 0.5,
        approvalPolicy: "always_external",
        createdAt: "2026-09-07T10:00:00.000Z",
      },
      {
        id: "mv_content_1",
        tenantId: TENANT,
        missionId: "mission_content",
        version: 1,
        immutable: false,
        outcome: "Sourced LinkedIn drafts from approved company facts.",
        knowledgeSourceIds: ["src_profile", "src_tone"],
        instructions:
          "Calm, precise, no hype. Every claim needs a source. Do not promise autonomy.",
        tools: ["document_read", "draft_document"],
        operatingMode: "test",
        budgetEur: 0.4,
        approvalPolicy: "always_external",
        createdAt: "2026-09-08T08:00:00.000Z",
      },
      {
        id: "mv_meeting_1",
        tenantId: TENANT,
        missionId: "mission_meeting",
        version: 1,
        immutable: true,
        outcome: "Meeting brief, questions and unknowns.",
        knowledgeSourceIds: ["src_profile"],
        instructions: "Do not invent attendee titles. Surface unknowns instead of guessing.",
        tools: ["document_read"],
        operatingMode: "supervised",
        budgetEur: 0.3,
        approvalPolicy: "never_for_test",
        createdAt: "2026-09-06T09:00:00.000Z",
      },
    ],
    sources: [
      {
        id: "src_profile",
        tenantId: TENANT,
        name: "Company profile",
        kind: "profile",
        status: "ready",
        origin: "workspace",
        excerpt: "Acme: B2B construction software for site teams in Europe.",
        version: "sv_1",
        required: true,
        createdAt: "2026-09-08T09:12:00.000Z",
      },
      {
        id: "src_request_104",
        tenantId: TENANT,
        name: "Request #104 — Vinci Lyon",
        kind: "fixture",
        status: "ready",
        origin: "fixture://request-104",
        excerpt:
          "Bonjour, nous devons déployer 12 licences sur le chantier Lyon-Confluence d'ici 48h, y compris le week-end. Merci de confirmer le tarif et les conditions.",
        version: "sv_104",
        required: false,
        createdAt: "2026-09-08T14:02:00.000Z",
      },
      {
        id: "src_catalog",
        tenantId: TENANT,
        name: "Offer notes (incomplete)",
        kind: "upload",
        status: "ready",
        origin: "upload://offer-notes.pdf",
        excerpt:
          "Standard license €89 / user / month. Onboarding is scoped per site. Weekend coverage is not priced in this document.",
        version: "sv_cat_1",
        required: false,
        createdAt: "2026-09-08T11:00:00.000Z",
      },
      {
        id: "src_tone",
        tenantId: TENANT,
        name: "Tone of voice",
        kind: "upload",
        status: "ready",
        origin: "upload://tone.md",
        excerpt: "Capable, precise, no sci-fi. Show evidence. Never claim full autonomy.",
        version: "sv_tone_1",
        required: false,
        createdAt: "2026-09-08T08:10:00.000Z",
      },
    ],
    instructions: [
      {
        id: "ins_prices",
        tenantId: TENANT,
        title: "Never invent prices",
        body: "If a price is not in an approved catalog version, mark it unknown and ask.",
        scope: "workspace",
        provenance: "Founder policy",
        status: "approved",
      },
      {
        id: "ins_fr",
        tenantId: TENANT,
        title: "Match the customer language",
        body: "Reply in the language of the request. Default to French for FR customers.",
        scope: "workspace",
        provenance: "Sales preference",
        status: "approved",
      },
    ],
    memory: [
      {
        id: "mem_weekend",
        tenantId: TENANT,
        kind: "procedural",
        title: "Weekend coverage is not in the catalog",
        body: "Do not quote weekend coverage. Ask for the constraint and route to a human.",
        scope: "general_rule",
        source: "Correction on request-analysis",
        owner: USER,
        confidence: 0.9,
        status: "approved",
        createdAt: "2026-09-08T17:00:00.000Z",
      },
    ],
    connections: [
      {
        id: "conn_notion",
        tenantId: TENANT,
        provider: "notion",
        label: "Notion",
        status: "needs_auth",
        scopes: ["read_pages", "read_databases"],
        secretRef: "secret://nango/notion",
        health: "Not connected",
      },
      {
        id: "conn_drive",
        tenantId: TENANT,
        provider: "google-drive",
        label: "Google Drive",
        status: "needs_auth",
        scopes: ["drive.readonly"],
        secretRef: "secret://nango/google-drive",
        health: "Not connected",
      },
      {
        id: "conn_hubspot",
        tenantId: TENANT,
        provider: "hubspot",
        label: "HubSpot",
        status: "needs_auth",
        scopes: ["crm.objects.contacts.read"],
        secretRef: "secret://nango/hubspot",
        health: "Not connected — required for lead operations",
      },
      {
        id: "conn_slack",
        tenantId: TENANT,
        provider: "slack",
        label: "Slack",
        status: "needs_auth",
        scopes: ["chat:write"],
        secretRef: "secret://nango/slack",
        health: "Not connected — writes blocked in test mode anyway",
      },
    ],
    runs: [
      {
        id: "run_meeting_ok",
        tenantId: TENANT,
        missionId: "mission_meeting",
        missionVersionId: "mv_meeting_1",
        mode: "test",
        state: "succeeded",
        workflowId: "wf_meeting_ok",
        policyVersion: "pol_1",
        policyHash: "a1b2c3d4e5f6a7b8",
        traceId: "tr_meeting_ok",
        inputText: "Prep for Vinci procurement, Lyon site rollout.",
        inputRefs: ["src_profile"],
        artifactIds: ["art_meeting"],
        evaluationId: "eval_meeting",
        steps: demoSteps("meeting-prep"),
        cost: { provider: 0.11, platform: 0.02, currency: "EUR" },
        model: "managed/quality-balanced",
        createdAt: "2026-09-08T16:00:00.000Z",
        completedAt: "2026-09-08T16:01:12.000Z",
        caseId: "case_vinci_meeting",
      },
      {
        id: "run_pending",
        tenantId: TENANT,
        missionId: "mission_request",
        missionVersionId: "mv_request_1",
        mode: "test",
        state: "waiting_approval",
        workflowId: "wf_request_104",
        policyVersion: "pol_1",
        policyHash: "c4d5e6f7a8b9c0d1",
        traceId: "tr_request_104",
        inputText: "Request #104 — Vinci Lyon weekend coverage.",
        inputRefs: ["src_request_104", "src_catalog", "src_profile"],
        artifactIds: ["art_request"],
        evaluationId: "eval_request",
        steps: demoSteps("request-analysis"),
        cost: { provider: 0.16, platform: 0.03, currency: "EUR" },
        model: "managed/quality-balanced",
        createdAt: "2026-09-08T21:36:00.000Z",
        completedAt: "2026-09-08T21:37:40.000Z",
        caseId: "case_104",
      },
    ],
    artifacts: [
      {
        id: "art_meeting",
        tenantId: TENANT,
        runId: "run_meeting_ok",
        kind: "brief",
        title: "Vinci procurement brief",
        body: "Vinci is asking about a Lyon-Confluence rollout. We can speak to license count and onboarding. Weekend coverage is not in the approved catalog.",
        citations: [
          {
            sourceId: "src_profile",
            sourceName: "Company profile",
            excerpt: "Acme helps site managers plan, quote and coordinate crews.",
          },
        ],
        unknowns: ["Weekend coverage terms", "Exact attendee title"],
      },
      {
        id: "art_request",
        tenantId: TENANT,
        runId: "run_pending",
        kind: "reply",
        title: "Prepared response — Vinci #104",
        body: "Bonjour Claire,\n\nNous avons bien reçu votre demande pour le chantier Lyon-Confluence (12 licences, mise en service sous 48h).\n\nNous pouvons préparer le déploiement des licences et l’onboarding site. La couverture week-end n’est pas dans le catalogue approuvé : nous ne pouvons pas en confirmer le tarif ici.\n\nUn chef de projet dédié n’est pas décrit dans les sources actuelles.\n\nPouvez-vous confirmer la contrainte de livraison week-end pour que nous puissions faire valider une offre ?\n\nCordialement,\nAcme",
        citations: [
          {
            sourceId: "src_request_104",
            sourceName: "Request #104 — Vinci Lyon",
            excerpt: "12 licences sur le chantier Lyon-Confluence d'ici 48h, y compris le week-end.",
          },
          {
            sourceId: "src_catalog",
            sourceName: "Offer notes (incomplete)",
            excerpt: "Weekend coverage is not priced in this document.",
          },
        ],
        unknowns: ["Weekend coverage terms and pricing", "Whether a dedicated project manager is included"],
      },
    ],
    evaluations: [
      {
        id: "eval_meeting",
        tenantId: TENANT,
        runId: "run_meeting_ok",
        packageSlug: "meeting-prep",
        checks: [
          { id: "identity", label: "Identity", status: "pass", detail: "Company and site named from sources." },
          { id: "citations", label: "Citations", status: "pass", detail: "Claims point at the company profile." },
          { id: "facts", label: "No unsupported facts", status: "pass", detail: "Unknowns listed instead of guessed." },
        ],
        score: 0.93,
        humanFeedback: { accepted: true, note: "Corrected attendee title once." },
        gatePassed: true,
      },
      {
        id: "eval_request",
        tenantId: TENANT,
        runId: "run_pending",
        packageSlug: "request-analysis",
        checks: [
          { id: "scope", label: "No invented prices", status: "pass", detail: "Weekend coverage flagged as unknown." },
          { id: "language", label: "Customer language", status: "pass", detail: "Reply is in French." },
          { id: "broker", label: "Writes blocked in test", status: "pass", detail: "send_email denied by the tool broker." },
        ],
        score: 0.91,
        gatePassed: true,
      },
    ],
    approvals: [
      {
        id: "appr_request",
        tenantId: TENANT,
        actionId: "act_send_reply",
        runId: "run_pending",
        payloadHash: "pending",
        status: "pending",
        preview: "Send prepared reply to Vinci for request #104. No price is stated.",
        consequence: "An email would leave the company. Test mode still blocks the send.",
        estimatedCostEur: 0.18,
        expiresAt: "2026-09-09T18:00:00.000Z",
      },
    ],
    actions: [
      {
        id: "act_send_reply",
        tenantId: TENANT,
        runId: "run_pending",
        kind: "send_email",
        state: "approval_required",
        payload: { to: "procurement@vinci.example", subject: "Re: Lyon-Confluence" },
        payloadHash: "pending",
        idempotencyKey: "act_send_reply_v1",
        approvalId: "appr_request",
      },
    ],
    budgets: [],
    usage: [
      {
        id: "use_1",
        tenantId: TENANT,
        runId: "run_meeting_ok",
        kind: "provider",
        amountEur: 0.11,
        note: "Managed model — meeting brief",
        createdAt: "2026-09-08T16:01:12.000Z",
      },
      {
        id: "use_2",
        tenantId: TENANT,
        runId: "run_meeting_ok",
        kind: "platform",
        amountEur: 0.02,
        note: "Platform fee",
        createdAt: "2026-09-08T16:01:12.000Z",
      },
      {
        id: "use_3",
        tenantId: TENANT,
        runId: "run_meeting_ok",
        kind: "human_review",
        amountEur: 0.0,
        note: "One correction, ~90 seconds",
        createdAt: "2026-09-08T16:04:00.000Z",
      },
    ],
    audit: [
      {
        id: "aud_1",
        tenantId: TENANT,
        actor: USER,
        action: "mission.test",
        target: "mission_meeting",
        result: "succeeded",
        policyHash: "a1b2c3d4e5f6a7b8",
        traceId: "tr_meeting_ok",
        createdAt: "2026-09-08T16:01:12.000Z",
      },
    ],
    outbox: [],
    cases: [
      {
        id: "case_104",
        tenantId: TENANT,
        packageSlug: "request-analysis",
        title: "Request #104 — Vinci Lyon",
        customer: "Vinci",
        historical: true,
        body: "Bonjour,\n\nNous devons déployer 12 licences Acme sur le chantier Lyon-Confluence d'ici 48 heures, y compris une couverture week-end pour l'équipe de nuit.\n\nPouvez-vous confirmer le tarif, le délai de mise en service, et si un chef de projet dédié est inclus ?\n\nCordialement,\nClaire Dupont\nProcurement, Vinci",
      },
      {
        id: "case_105",
        tenantId: TENANT,
        packageSlug: "request-analysis",
        title: "Request #105 — Bouygues Nantes",
        customer: "Bouygues",
        historical: true,
        body: "Hello, we need a quote for 8 licenses and onboarding next month. No weekend work. Please send pricing.",
      },
      {
        id: "case_research",
        tenantId: TENANT,
        packageSlug: "research-brief",
        title: "French construction-software tenders",
        historical: false,
        body: "Who is winning public construction software tenders in France this quarter, and what do they ask for?",
      },
      {
        id: "case_content",
        tenantId: TENANT,
        packageSlug: "content-draft",
        title: "LinkedIn — quote rework",
        historical: false,
        body: "Write a LinkedIn post on how construction SMEs lose a week per month to quote rework.",
      },
      {
        id: "case_vinci_meeting",
        tenantId: TENANT,
        packageSlug: "meeting-prep",
        title: "Vinci procurement — Lyon",
        customer: "Vinci",
        historical: true,
        body: "Prep for tomorrow's call with Vinci procurement on the Lyon-Confluence site rollout.",
      },
    ],
    decisions: [
      {
        id: "dec_104",
        tenantId: TENANT,
        missionId: "mission_request",
        approvalId: "appr_request",
        title: "Customer request · Vinci",
        missionName: "Analyze incoming customer requests",
        reason: "Missing one delivery constraint. Reply is ready.",
        source: "Request #104",
        estimatedCostEur: 0.18,
        consequence: "Approving in supervised mode prepares a send. Test mode will still block the email.",
        createdAt: "2026-09-08T21:38:00.000Z",
        kind: "inspect",
        whyNow: "Vinci asked for weekend coverage. The catalog does not have it. The reply is ready without a price.",
      },
      {
        id: "dec_content",
        tenantId: TENANT,
        missionId: "mission_content",
        title: "Content draft · LinkedIn",
        missionName: "Sourced LinkedIn drafts",
        reason: "Two claims need confirmation before the draft can be kept.",
        source: "4 sources",
        estimatedCostEur: 0.12,
        consequence: "Keeping the draft stores it. Publishing remains blocked.",
        createdAt: "2026-09-08T18:10:00.000Z",
        kind: "review",
        whyNow: "Tone and profile exist. Publishing is still off. This is a keep-or-edit, not a send.",
      },
    ],
    signals: [
      {
        id: "sig_1",
        slug: "request-analysis",
        title: "Inbound requests already arrive",
        whyNow: "A real Vinci email is in the workspace. First useful result does not need an external write.",
        evidence: "Request #104 · missing weekend coverage",
        strength: 0.94,
      },
      {
        id: "sig_2",
        slug: "meeting-prep",
        title: "A named meeting is tomorrow",
        whyNow: "Prep is cheaper than discovering the gap in the room.",
        evidence: "Vinci procurement · Lyon-Confluence",
        strength: 0.88,
      },
      {
        id: "sig_3",
        slug: "content-draft",
        title: "Tone is already approved",
        whyNow: "The second capability reuses the company profile. Only the channel is missing.",
        evidence: "Tone of voice source ready",
        strength: 0.76,
      },
    ],
    copilot: [
      {
        id: "cop_1",
        title: "Replay request #104 with the weekend rule",
        when: "Next 15 min",
        missionId: "mission_request",
        kind: "test",
      },
      {
        id: "cop_2",
        title: "Approve Vinci reply payload, or let it expire",
        when: "Today 18:00",
        missionId: "mission_request",
        kind: "approval",
      },
      {
        id: "cop_3",
        title: "Confirm two LinkedIn claims",
        when: "Today",
        missionId: "mission_content",
        kind: "run",
      },
    ],
    impact: {
      hoursSaved: 6.5,
      acceptedResultCostEur: 0.14,
      secondCapabilityMinutes: 4,
      correctionRate: 0.18,
      runsThisWeek: 11,
    },
  };
}
