/**
 * Orbi mascot assets. Originals live in public/brand/orbi/{mood}.png (1254 px); the
 * derivatives below are generated by scripts/orbi-assets.mjs. Rules: docs/design/orbi-mascot.md.
 */
export const ORBI_MOODS = ["welcome", "thinking", "done", "team"] as const;
export type OrbiMood = (typeof ORBI_MOODS)[number];

/** Derivative widths on disk (square). Keep in sync with scripts/orbi-assets.mjs. */
export const ORBI_SIZES = [64, 128, 256, 512] as const;

/** Below this rendered size the 3D character turns to mush: use the OrbiMark SVG instead. */
export const ORBI_MIN_SIZE = 32;

/** Smallest derivative that covers `px` device pixels (the largest one otherwise). */
export function orbiAssetWidth(px: number): (typeof ORBI_SIZES)[number] {
  return ORBI_SIZES.find((w) => w >= px) ?? ORBI_SIZES[ORBI_SIZES.length - 1];
}

/** 1x / 2x srcsets per format, so a 64 px Orbi downloads ~3 KB instead of the 1 MB original. */
export function orbiSources(mood: OrbiMood, size: number) {
  const one = orbiAssetWidth(size);
  const two = orbiAssetWidth(size * 2);
  const url = (w: number, ext: "avif" | "webp") => `/brand/orbi/${mood}-${w}.${ext}`;
  const set = (ext: "avif" | "webp") => (one === two ? url(one, ext) : `${url(one, ext)} 1x, ${url(two, ext)} 2x`);
  return { avif: set("avif"), webp: set("webp"), fallback: url(one, "webp") };
}
