import type { CapabilityPackage } from "@/lib/domain/types";

export const PACKAGES: CapabilityPackage[] = [
  {
    slug: "research-brief",
    version: "0.1.0",
    name: "Research brief",
    outcome: "A sourced, prioritized brief you can act on.",
    description:
      "Turn a question into a ranked set of findings with citations, freshness checks and explicit unknowns.",
    maturity: "ready",
    owner: "internal-team",
    category: "Research",
    roles: ["Founder", "Strategy", "Sales"],
    tools: ["search", "document_read"],
    industries: ["Any"],
    inputs: ["question", "scope", "sources"],
    outputs: ["brief", "citations", "unknowns"],
    requiredKnowledge: ["Company profile"],
    externalEffects: [],
    evaluations: ["citation_coverage", "relevance", "duplicate_rate"],
    exampleInput: "Who is winning public construction software tenders in France this quarter?",
    exampleResult: "Prioritized findings with dated sources and a short list of what remains unknown.",
    testTime: "90 seconds",
    firstUsefulResult: "Sourced and prioritized findings",
    protocol: ["Research", "Filter", "Cite", "Review"],
    costBoundEur: 0.35,
    risks: ["Stale web pages", "Duplicate coverage"],
    approvalPoints: ["never_for_test"],
    failureModes: ["No citable source", "Question too broad"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
  {
    slug: "meeting-prep",
    version: "0.1.0",
    name: "Meeting preparation",
    outcome: "A brief, questions and unknowns before you walk in.",
    description:
      "Prepare a meeting from the company profile, selected documents and the attendee context. Never invent facts.",
    maturity: "ready",
    owner: "internal-team",
    category: "Operations",
    roles: ["Founder", "Sales", "Account"],
    tools: ["document_read"],
    industries: ["Any"],
    inputs: ["meeting_context", "attendees", "sources"],
    outputs: ["brief", "questions", "unknowns"],
    requiredKnowledge: ["Company profile"],
    externalEffects: [],
    evaluations: ["identity_check", "citation_coverage", "unsupported_claim_rate"],
    exampleInput: "Prep for tomorrow's call with Vinci procurement on the Lyon site rollout.",
    exampleResult: "One-page brief, five questions, and a list of facts we cannot yet confirm.",
    testTime: "75 seconds",
    firstUsefulResult: "Brief, questions and unknowns",
    protocol: ["Identify", "Extract", "Draft", "Verify"],
    costBoundEur: 0.28,
    risks: ["Wrong attendee identity", "Unsupported claims"],
    approvalPoints: ["never_for_test"],
    failureModes: ["Missing attendee context"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
  {
    slug: "content-draft",
    version: "0.1.0",
    name: "Sourced content draft",
    outcome: "A draft plus channel variants, each claim tied to a source.",
    description:
      "Write from approved knowledge only. Claims without a source are flagged. Publishing stays off until you say so.",
    maturity: "ready",
    owner: "internal-team",
    category: "Growth",
    roles: ["Founder", "Marketing"],
    tools: ["document_read", "draft_document"],
    industries: ["Any"],
    inputs: ["brief", "channel", "sources"],
    outputs: ["draft", "variants", "citations"],
    requiredKnowledge: ["Company profile", "Tone instructions"],
    externalEffects: [],
    evaluations: ["source_coverage", "instruction_fit", "format"],
    exampleInput: "LinkedIn post on how construction SMEs lose a week per month to quote rework.",
    exampleResult: "Draft plus LinkedIn and newsletter variants, with two claims marked for confirmation.",
    testTime: "80 seconds",
    firstUsefulResult: "Draft plus channel variants",
    protocol: ["Gather", "Draft", "Cite", "Adapt"],
    costBoundEur: 0.32,
    risks: ["Unsourced claims", "Off-tone copy"],
    approvalPoints: ["never_for_test", "always before publish"],
    failureModes: ["Missing brand voice"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
  {
    slug: "request-analysis",
    version: "0.4.0",
    name: "Customer-request analysis",
    outcome: "A structured need and a prepared reply, with missing fields named.",
    description:
      "Read an incoming request, extract requirements, compare against approved facts, and prepare a response. Prices are never invented.",
    maturity: "ready",
    owner: "internal-team",
    category: "Customer Care",
    roles: ["Founder", "Sales", "Support"],
    tools: ["read_approved_sources", "create_artifact"],
    industries: ["Any"],
    inputs: ["request_document"],
    outputs: ["request_summary", "prepared_reply", "unknowns"],
    requiredKnowledge: ["Company profile", "Offer catalog"],
    externalEffects: [],
    evaluations: ["requirement_coverage", "unsupported_claim_rate", "human_acceptance"],
    exampleInput: "Email from Vinci asking for a 48h site rollout and weekend coverage.",
    exampleResult: "Structured need, prepared French reply, and one missing delivery constraint.",
    testTime: "70 seconds",
    firstUsefulResult: "Structured need and prepared response",
    protocol: ["Read", "Extract", "Match facts", "Detect gaps", "Draft", "Verify"],
    costBoundEur: 0.22,
    risks: ["Invented prices", "Missing constraints"],
    approvalPoints: ["never_for_test", "always before send"],
    failureModes: ["Missing catalog", "Ambiguous request"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
  {
    slug: "quote-prep",
    version: "0.2.0",
    name: "Quote preparation",
    outcome: "A draft quote with assumptions, integer money math, human approval.",
    description:
      "Compose a reviewable quote from catalog and request. Calculations are deterministic. Sending is blocked until approval.",
    maturity: "composable",
    owner: "internal-team",
    category: "Sales",
    roles: ["Founder", "Sales", "Finance"],
    tools: ["read_docs", "calculate", "draft_document"],
    industries: ["B2B", "Construction", "Services"],
    inputs: ["customer_request", "catalog"],
    outputs: ["quote_draft", "assumptions"],
    requiredKnowledge: ["Approved catalog", "Margin policy"],
    externalEffects: ["create_quote"],
    evaluations: ["money_math", "catalog_version", "human_approval"],
    exampleInput: "Quote for Vinci Lyon: 12 licenses, onboarding, weekend coverage.",
    exampleResult: "Draft quote with assumptions and a blocked send action.",
    testTime: "2 minutes",
    firstUsefulResult: "Draft quote with assumptions",
    protocol: ["Extract", "Price", "Assume", "Draft", "Approve"],
    costBoundEur: 0.5,
    risks: ["Wrong catalog version", "Margin below threshold"],
    approvalPoints: ["always before send"],
    failureModes: ["Missing price", "Legal uncertainty"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
  {
    slug: "tender-analysis",
    version: "0.1.0",
    name: "Tender analysis",
    outcome: "Eligibility, deadlines and missing documents, with citations.",
    description:
      "Read a public tender, score eligibility, list deadlines and flag missing documents. No unsupervised filing.",
    maturity: "planned",
    owner: "internal-team",
    category: "Sales",
    roles: ["Founder", "Bid"],
    tools: ["document_read"],
    industries: ["Public sector", "Construction"],
    inputs: ["tender_pack"],
    outputs: ["eligibility", "deadlines", "gaps"],
    requiredKnowledge: ["Company profile", "Certifications"],
    externalEffects: ["submit_tender"],
    evaluations: ["requirement_coverage", "citation_coverage", "risk_flags"],
    exampleInput: "AO-2026-441 for a construction SaaS framework agreement.",
    exampleResult: "Eligibility map, deadline list, missing document pack.",
    testTime: "3 minutes",
    firstUsefulResult: "Eligibility, deadlines and missing documents",
    protocol: ["Parse", "Score", "Cite", "Flag"],
    costBoundEur: 0.6,
    risks: ["Missed deadline", "Wrong eligibility"],
    approvalPoints: ["always before submit"],
    failureModes: ["Unreadable scan"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
  {
    slug: "lead-ops",
    version: "0.1.0",
    name: "Lead operations",
    outcome: "Enrichment, scoring and a follow-up draft. CRM stays source of truth.",
    description:
      "Enrich and score inbound leads, draft a follow-up. Writes to CRM wait for approval. Consent policy is enforced.",
    maturity: "planned",
    owner: "internal-team",
    category: "Growth",
    roles: ["Founder", "Growth", "Sales"],
    tools: ["crm_read", "enrich", "draft_document"],
    industries: ["B2B"],
    inputs: ["lead", "consent_policy"],
    outputs: ["enriched_lead", "score", "follow_up"],
    requiredKnowledge: ["ICP", "Consent policy"],
    externalEffects: ["crm_write", "send_email"],
    evaluations: ["dedupe", "consent_policy", "crm_authority"],
    exampleInput: "Inbound from a 40-person construction firm in Lyon.",
    exampleResult: "Enriched record, score, follow-up draft waiting for send.",
    testTime: "2 minutes",
    firstUsefulResult: "Enrichment, scoring and follow-up draft",
    protocol: ["Dedupe", "Enrich", "Score", "Draft", "Approve"],
    costBoundEur: 0.4,
    risks: ["Duplicate records", "Consent breach"],
    approvalPoints: ["always before CRM write or send"],
    failureModes: ["No CRM connection"],
    deprecationPolicy: "Versions remain runnable for 90 days after sunset.",
  },
];

export function getPackage(slug: string) {
  return PACKAGES.find((item) => item.slug === slug);
}
