#!/usr/bin/env bash
# Local production-like stack: Supabase (Postgres + Auth + Mailpit) in Docker,
# migrations applied by the owner role, app connected as a runtime role
# without BYPASSRLS (same shape as production, see docs/product/launch-checklist.md).
#
#   pnpm local:up      start Supabase, create the runtime role, migrate
#   pnpm local:env     print the .env.local block to paste
#   pnpm local:down    stop containers (data kept)
#
# Magic-link e-mails land in Mailpit: http://127.0.0.1:54324
set -euo pipefail

cd "$(dirname "$0")/.."
SUPABASE="npx -y supabase@2"
OWNER_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
APP_ROLE="orbis_app"
APP_PASSWORD="orbis_app_local"
APP_URL="postgresql://${APP_ROLE}:${APP_PASSWORD}@127.0.0.1:54322/postgres"

up() {
  $SUPABASE start -x studio,imgproxy,edge-runtime,logflare,vector,realtime,storage-api,postgres-meta,supavisor
  docker exec -i supabase_db_orbis psql -v ON_ERROR_STOP=1 -U postgres -d postgres <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_ROLE}') THEN
    CREATE ROLE ${APP_ROLE} LOGIN PASSWORD '${APP_PASSWORD}' NOSUPERUSER NOBYPASSRLS NOCREATEROLE NOCREATEDB;
  END IF;
END \$\$;
SQL
  MIGRATION_DATABASE_URL="$OWNER_URL" DATABASE_APP_ROLE="$APP_ROLE" node --import tsx scripts/migrate.ts
  echo
  echo "Local stack ready. Run: pnpm local:env, paste into .env.local, then pnpm dev."
}

env_block() {
  local status
  status=$($SUPABASE status -o env 2>/dev/null)
  local api_url publishable service_role
  api_url=$(sed -n 's/^API_URL="\(.*\)"/\1/p' <<<"$status")
  publishable=$(sed -n 's/^PUBLISHABLE_KEY="\(.*\)"/\1/p' <<<"$status")
  [ -n "$publishable" ] || publishable=$(sed -n 's/^ANON_KEY="\(.*\)"/\1/p' <<<"$status")
  service_role=$(sed -n 's/^SECRET_KEY="\(.*\)"/\1/p' <<<"$status")
  [ -n "$service_role" ] || service_role=$(sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"/\1/p' <<<"$status")
  cat <<ENV
# --- Orbis local stack (generated by scripts/local-stack.sh) ---
APP_ORIGIN=http://127.0.0.1:3000
ORBIS_APP_URL=http://127.0.0.1:3000
NEXT_PUBLIC_SUPABASE_URL=${api_url}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishable}
SUPABASE_SERVICE_ROLE_KEY=${service_role}
DATABASE_URL=${APP_URL}
MIGRATION_DATABASE_URL=${OWNER_URL}
DATABASE_APP_ROLE=${APP_ROLE}
CRON_SECRET=local-cron-secret-change-me-0123456789abcdef
ORBIS_RATE_LIMIT_SECRET=local-rate-limit-secret-0123456789abcdef
ORBIS_INBOX_DRAFTS_ENABLED=true
ORBIS_INBOX_MODE=test
ORBIS_DIGEST=true
ENV
}

case "${1:-up}" in
  up) up ;;
  env) env_block ;;
  down) $SUPABASE stop ;;
  *) echo "usage: $0 up|env|down" >&2; exit 1 ;;
esac
